# Рабочая тетрадь 2

# 1.3.1. Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
import numpy as np

A = np.zeros((8,8))
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 1.3.2. Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [ ]:
import numpy as np

x=np.zeros((5,5))
x+= np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 1.3.3. Задание
Создать массив 3x3x3 со случайными значениями.


In [ ]:
import numpy as np

A = np.random.random((3,3,3))
print(A)

[[[0.59839926 0.30503859 0.80743435]
  [0.4576804  0.02611428 0.00612641]
  [0.34562812 0.42138443 0.66879233]]

 [[0.6681481  0.98891329 0.80656344]
  [0.72404165 0.81264861 0.09729036]
  [0.05177839 0.99206116 0.87818215]]

 [[0.61306446 0.87132427 0.37197736]
  [0.45048168 0.08166333 0.60017773]
  [0.00622394 0.15594671 0.58227151]]]


# 1.3.4. Задание
Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
import numpy as np

A = np.ones((5,5))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 1.3.5. Задание
Создайте массив и отсортируйте его по убыванию.

In [ ]:
import numpy as np

arr = np.random.randint(1,15,10)
print(arr)
print(np.sort(arr)[::-1])

[ 3 10 11 12  2 10 11  8  3  9]
[12 11 11 10 10  9  8  3  3  2]


# 2.3.1. Задание
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [ ]:
import pandas as pd

a = pd.Series([2, 6, 3, 8])
b = pd.Series([1, 9, 4, 7])

sum((a - b)**2)**0.5

3.4641016151377544

# 2.3.2. Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

# 2.3.3. Задание
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)

dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [ ]:
dataframe.iloc[1:4]

age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

In [ ]:
dataframe[dataframe['gender'] == 'Female'].head(5)

age workclass  education_num         marital_status       occupation  \
4    28   Private             13     Married-civ-spouse   Prof-specialty   
5    37   Private             14     Married-civ-spouse  Exec-managerial   
6    49   Private              5  Married-spouse-absent    Other-service   
8    31   Private             14          Never-married   Prof-specialty   
12   23   Private             13          Never-married     Adm-clerical   

     relationship   race  gender  hours_per_week native_country  capital  \
4            Wife  Other  Female              40          Other        0   
5            Wife  White  Female              40  United-States        0   
6   Not-in-family  Other  Female              16          Other        0   
8   Not-in-family  White  Female              50  United-States    14084   
12      Own-child  White  Female              30  United-States        0   

   income_status  
4          <=50K  
5          <=50K  
6          <=50K  
8           >50K  
12         <=50K

# 3.3.2. Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

# создание фрейма данных
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
# нормализация первого числового признака (sepal_length_cm) с использованием минимаксного преобразования
scaler1 = MinMaxScaler()
dataframe[['sepal_length_cm']] = scaler1.fit_transform(dataframe[['sepal_length_cm']])
# нормализация второго числового признака (sepal_width_cm) с задействованием z-масштабирования
scaler2 = StandardScaler()
dataframe[['sepal_width_cm']] = scaler2.fit_transform(dataframe[['sepal_width_cm']])

dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]